2016Q4.vanishingpoint-copyover
chalmers-revere/opendlv pull request #111
Opened 2016-11-09 15:31 UTC by crispin-kirchner

2016-11-09 15:33 UTC, bjornborg commented
Shouldn't this be PR into pre-release?

2016-11-09 16:01 UTC, crispin-kirchner commented
@bjornborg thanks for pointing this out, I forgot

2016-11-09 18:39 UTC, bjornborg commented
I got your back.

2016-11-10 10:07 UTC, crispin-kirchner commented
thanks ;)

2016-11-23 17:40 UTC, chrberger requested changes
Please remove all images where license plates are readable.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/apps/LaneMarkingsVanishingPointDetectionModule.cpp
> +#include <cstdlib>
Please add the default License header and your name as author.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/apps/LaneMarkingsVanishingPointDetectionModule.cpp
> +    VanishingPointLowPass(float dampingFactor) : dampingFactor_(dampingFactor), lastVanishingPoint_() { }
The argument should be changed to "const float &dampingFactor".

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/apps/ImageProcessingTestFixture.cpp
> +#include <iostream>
Please add a short License header and a few lines of explanation for the purpose of this file.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/apps/LaneMarkingsVanishingPointDetectionModule.cpp
> +class VanishingPointLowPass {
Please separate the classes into a header and implementation file.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/apps/LaneMarkingsVanishingPointDetectionModule.cpp
> +class SharedImageCvAdapter {
Please separate the classes into a header and implementation file.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/apps/LaneMarkingsVanishingPointDetectionModule.cpp
> +class LaneMarkingsVanishingPointDetectionModule : public DataTriggeredConferenceClientModule {
Please separate the classes into a header and implementation file (separate header and implementation files for the individual classes).

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/apps/LaneMarkingsVanishingPointDetectionModule.cpp
> +#ifndef NDEBUG
Please let this function be part of the regular source tree and use if based on the value of your DEBUG_IS_SET value.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/ConfigDeserialization.h
> +#ifndef CONFIG_DESERIALIZATION_H_
Please add the License header and your name as author.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/ImagePreprocessing.h
> +#ifndef IMAGE_PREPROCESSING_H_
Please add a License header and your name as author.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/ImagePreprocessing.h
> +    AstaZeroImagePreprocessing(int blurSize, uint8_t threshold) : blurSize_(blurSize), threshold_(threshold) {
Please have the implementation in separate implementation files.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/ImagePreprocessing.h
> +    cv::Mat preprocessImage(cv::Mat & coloredImage) const {
Same here.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/LaneMarkingsScan.h
> +#ifndef LANE_MARKINGS_SCAN_H_
Please add a License header and your name.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/LaneMarkingsScan.h
> +    LaneMarkingsScanner(RelativeDirection scanDirection, const ScanRegion & scanRegion,
Please have the implementation in separate implementation files (please apply this for all further occurrences).

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/MatVisitInterface.h
> +#ifndef MAT_VISIT_INTERFACE_H_
Cf above.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/RegionOfInterestGeometry.h
> +#ifndef REGION_OF_INTEREST_GEOMETRY_H_
Cf. above.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/ScanRegion.h
> +#ifndef LANE_MARKINGS_SCAN_REGION_H_
Cf. above.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/VanishingPointDetection.h
> +#ifndef LANE_MARKINGS_DETECTION_H_
Cf. above.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/include/VanishingPointDetection.h
> +#ifndef LANE_MARKINGS_DETECTION_H_
Once you have adjusted the sources, please run https://github.com/chalmers-revere/opendlv/blob/master/scripts/refactorCWD.sh on your sub-tree to let clang reformat your sources to follow our coding style.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/src/LmvpTypes.cpp
> +#include "LmvpTypes.h"
Cf. above.

2016-11-23 17:40 UTC, chrberger commented on code/system/application/legacy/vanishingpoint/src/MatVisitInterface.cpp
> +#include "MatVisitInterface.h"
Cf. above.

2016-11-24 10:29 UTC, crispin-kirchner commented on code/system/application/legacy/vanishingpoint/apps/LaneMarkingsVanishingPointDetectionModule.cpp
> +    VanishingPointLowPass(float dampingFactor) : dampingFactor_(dampingFactor), lastVanishingPoint_() { }
Thank you for the review. What is our rationale behind passing primitive data types by reference?

2017-01-30 16:06 UTC, bjornborg commented
Ping @crispin-kirchner Status update?

2017-01-30 16:17 UTC, crispin-kirchner commented
The code in this branch is based on the CaroloCup algorithm and has become oblosete by the Hough-based implementation I made later. Shall I delete the branch?

2017-02-03 13:05 UTC, closed without merging

2017-02-03 13:05 UTC, bjornborg commented
Since it's absolete, I've closed the branch and PR.